var _tmr=_tmr||[];
(function(){function vb(){return S&&wb&&Wa?(Xa=[wb-S,Wa-S,Ia?Ia-S:null,Ja?Ja-S:null].join("/"),Ia&&Ja&&(vb=function(){return Xa}),Xa):null}function s(a,b,c){a.addEventListener?a.addEventListener(b,c,!1):a.attachEvent&&a.attachEvent("on"+b,c)}function K(a,b,c){a.removeEventListener?a.removeEventListener(b,c,!1):a.detachEvent&&a.detachEvent("on"+b,c)}function xb(a,b){try{if(a.nodeName.toLowerCase()===b.toLowerCase())return a;if(a.parentNode)return xb(a.parentNode,b)}catch(c){p&&console.warn("[TopMailRu] Error#1.25",c)}return null}
function yb(a,b){if(null===a.offsetParent||(0==a.offsetHeight||0==a.offsetWidth||0==a.clientHeight||0==a.clientWidth)||b&&(0==a.offsetLeft||0==a.offsetTop))return!1;if(void 0!==f.getComputedStyle){var c=f.getComputedStyle(a,null);return"none"!==c.display&&"hidden"!==c.visibility}return!0}function L(a,b){for(var c=0,d=b.length;c<d;c++)if(b[c]==a)return!0;return!1}function Q(a){var b=typeof a;return!("number"===b||"boolean"===b||"string"===b||a.nodeType||a===a.window)}function T(a){return"[object Array]"===
Object.prototype.toString.call(a)}function ja(){var a=arguments,b=a[0]||{},c=!1,d=1,e=a.length,h,g,l,n,f;"boolean"===typeof b&&(c=b,b=a[d++]||{});for(Q(b)||(b={});d<e;d++)if(null!=(h=a[d]))for(g in h)l=b[g],n=h[g],b!==n&&(c&&n&&(Q(n)||(f=T(n)))?(f?(f=!1,l=l&&T(l)?l:[]):l=l&&Q(l)?l:{},b[g]=ja(c,l,n)):void 0!==n&&(b[g]=n));return b}function fc(a,b,c){if(!a)return null;var d=a.match(b),e=2<arguments.length?c:0;return d&&d.length>e?d[e]:null}function zb(a){return(""+a).replace(/[\/\^\$\*\+\?\.\|\(\)\[\]\{\}\\]/g,
"\\$&")}function Ab(a){var b="";try{var c=new Uint8Array(a);f.crypto.getRandomValues(c);for(var d=0;d<a;d++)b+=(c[d]%16).toString(16)}catch(e){b="";for(d=0;d<a;d++)c=Math.floor(16*Math.random()),b+=c.toString(16)}return b}function w(){return(new Date).getTime()}function z(a,b){var c={data:b,raw:a,url:Ya(a)},d;if(!gc||"function"!==typeof navigator.sendBeacon)d=!1;else{c.dataSplitter=";";var e=Za(c.data,c.dataSplitter);try{d=!0===navigator.sendBeacon(c.url,e)}catch(h){d=!1}}d||(void 0===b?(c.dataSplitter=
";",c.open=hc,c.connect=ic,c.startListen=jc,c.stopListen=kc,c.open(c),c.connect(c)):("function"===typeof f.XMLHttpRequest?(c.dataSplitter=";",c.open=lc,c.connect=mc,c.startListen=nc,c.stopListen=oc,c.open(c),c.connect(c),d=!0):d=!1,d||pc(c)))}function pc(a){var b=k.createElement("iframe"),c=k.createElement("div");c.setAttribute("style","position: absolute !important; top: -9999px !important; left: -9999px !important; width: 1px !important; height: 1px !important;");c.appendChild(b);k.body.appendChild(c);
try{var d=b.contentWindow.document,e=d.createElement("div"),h;for(h in a.data)if(a.data.hasOwnProperty(h)){var g=a.data[h],l=typeof g;if("string"===l||"number"===l){var n=d.createElement("input");n.setAttribute("type","hidden");n.setAttribute("name",h);n.value=g;e.appendChild(n)}}var f=d.createElement("form");f.setAttribute("action",a.url);f.setAttribute("method",Bb);f.setAttribute("enctype",Cb);f.appendChild(e);var m=d.createElement("div");m.appendChild(f);d.body.appendChild(m);var A=function(){try{K(b,
"load",A),k.body.removeChild(c)}catch(a){p&&console.warn("[TopMailRu] Error#1.2",a)}};s(b,"load",A);f.submit()}catch(r){p&&console.warn("[TopMailRu] Error#1.3",r)}}function lc(a){a._connection=new f.XMLHttpRequest}function mc(a){a._connection.open(Bb,a.url);a._connection.setRequestHeader("Content-Type",Cb);a._connection.send(Za(a.data,a.dataSplitter))}function nc(a){s(a._connection,"load",a._onload);s(a._connection,"error",a._onerror)}function oc(a){K(a._connection,"load",a._onload);K(a._connection,
"error",a._onerror)}function hc(a){a._connection=new Image}function ic(a){a._connection.src=a.url+Za(a.data,a.dataSplitter)}function jc(a){a._connection.onload=a._onload;a._connection.onerror=a._onerror}function kc(a){a._connection.onload=null;a._connection.onerror=null}function Za(a,b){var c=b||";",d="",e;for(e in a)if(a.hasOwnProperty(e)){var h=a[e],g=typeof h;if("string"===g||"number"===g)d+=c+escape(e)+"="+escape(h)}return d}function Ya(a){return"https://top-fwz1.mail.ru"+a}function U(a){return(a=
k.cookie.match(RegExp("(?:^|; )"+a.replace(/([\.$?*|{}\(\)\[\]\\\/\+^])/g,"\\$1")+"=([^;]*)")))?decodeURIComponent(a[1]):null}function ra(a,b,c){c=c||{};var d=c.expires;"number"===typeof c.expires&&(d=new Date,d.setTime(d.getTime()+c.expires));d&&d.toUTCString&&(d=d.toUTCString());c.expires=d;a=a+"="+encodeURIComponent(b);for(var e in c)if((b=c[e])||0===b)a+="; "+e,!0!==b&&(a+="="+b);k.cookie=a}function $a(a,b){var c=b||{};c.expires=-1;ra(a,"",c)}function qc(){var a="tmr"+(""+Math.random()).slice(2);
try{return ka=f.localStorage||null,ka.setItem(a,a),ka.removeItem(a),!0}catch(b){return ka=null,p&&console.warn("[TopMailRu] Error#1.4",b),!1}}function La(a){try{return ka.getItem(a)}catch(b){p&&console.warn("[TopMailRu] Error#1.5",b)}return null}function Ma(a,b){try{ka.setItem(a,b)}catch(c){p&&console.warn("[TopMailRu] Error#1.6",c)}}function rc(){if(!la)return null;for(var a=x.hostname.split(".").reverse(),b,c=1,d=a.length;c<d;c++){b=a[0];for(var e=1;e<=c;e++)b=a[e]+"."+b;var e=""+w(),h={domain:b,
path:"/",expires:3E5};try{ra("tmr_tcdhn",e,h);var g=U("tmr_tcdhn");$a("tmr_tcdhn",h);if(g===e)return b}catch(l){p&&console.warn("[TopMailRu] Error#1.8",l)}}return null}function Db(a,b){la&&ra(a,b,ab);oa&&Ma(a,b)}function Eb(a){var b=k.createElement("script");b.type="text/javascript";b.async=!0;b.src=a;document.body.appendChild(b)}function Fb(a){var b=";e="+escape("detect");z(I(a,"/tracker",!1,!1)+b)}function Gb(a,b){if(a.length&&null!==b.ecom_data){var c=wa(b.ecom_data),c=c?(""+c).substring(1,c.length-
1):"";if(!(4096<c.length||-1===c.search(/\S/))){var d=bb("_m",b.ecom_method),e=bb("_t",b.ecom_type),h=bb("_jst",Hb()),c="{"+c+d+e+h+"}";z(I({id:a[0]},"/datalayer",!1,!0)+(";ids="+escape(a.join()))+(";e="+escape(c)))}}}function bb(a,b){var c=',"'+a+'":';if(!b||!b.length)return c+"[]";try{return c+'["'+b.join('","')+'"]'}catch(d){}return c+"false"}function sc(){var a=U(Ib);if(null===a)return null;a=a.split("|");if(3!==a.length)return null;var b=a[2],b=w()-b;return 0>b||b>Jb?null:{id:a[0],version:a[1]}}
function Kb(a){cb=!0;a.length&&Eb(Ya("/js/dyn-goal-config.js?ids="+a.join(",")))}function m(){}function sa(a){a&&"object"===typeof a&&(!V&&"id"in a)&&(V=a.id)}function tc(a){return(a=!W?void 0:W[a])&&Na?a-Na:void 0}function Lb(){if(W){for(var a=0,b="domInteractive domContentLoadedEventStart domContentLoadedEventEnd domComplete loadEventStart loadEventEnd".split(" "),c=0;c<b.length;c++){var d=!W?void 0:W[b[c]];if(0<d&&(d<a||0==a))a=d}return a?a:void 0}}function X(a,b){var c=1<arguments.length?b:V;
return a&&"object"===typeof a&&("id"in a&&a.id||c)}function I(a,b,c,d){oa&&Ma(ta,++F);var e="id"in a?a.id:V,h="url"in a?a.url:x.href,g="referrer"in a?a.referrer:k.referrer,l="title"in a?a.title:k.title,n;n=db;null===n&&(n=uc());n=null!==n?n?1:0:null;var Ka="userid"in a?a.userid:Y||0===Y?Y:void 0,m=Z?Z:void 0,A;A=ma&&a.bfCache;var r="pageView"===a.type&&a.timespent,q=[];V&&e!==V&&q.push("sec");"dataLayer"in f&&q.push("dl");C&&q.push(["ecom"].concat(C).join("-"));var xa=vc();xa&&xa.length&&q.push(["jst"].concat(xa).join("-"));
A&&q.push("bfc");M&&r&&q.push("ts");f.top!==f&&q.push("frame");A=q.join(",");var eb=f.screen,r=(new Date).getTimezoneOffset(),q="";if(f.Intl)try{q=f.Intl.DateTimeFormat().resolvedOptions().timeZone||""}catch(wc){p&&console.warn("[TopMailRu] Error#1.1",wc)}xa=r+"/"+q;r=Mb;r=null!==r?r:sc();q=vb();a.start=Lb();b=b+"?_="+Math.random()+(e?";id="+escape(e):"")+(h?";u="+escape(h):"")+(g?";r="+escape(g):"")+(a.start?";st="+escape(a.start):"")+("gender"in a?";gender="+escape(a.gender):"")+("age"in a?";age="+
escape(a.age):"")+("pid"in a?";pid="+escape(a.pid):"")+(void 0!==Ka?";userid="+escape(Ka):"")+(void 0!==m?";uparams="+escape(wa(m)):"")+(d&&l?";title="+encodeURIComponent(l):"")+(eb?";s="+eb.width+"*"+eb.height:"")+";vp=";e=d=0;k.documentElement&&(k.documentElement.clientWidth||k.documentElement.clientHeight)?(d=k.documentElement.clientWidth,e=k.documentElement.clientHeight):"number"==typeof f.innerWidth&&(d=f.innerWidth,e=f.innerHeight);b=b+(""+d+"*"+e)+";touch="+xc+";hds="+yc+";sid="+fb+";ver="+
zc+";tz="+encodeURIComponent(xa);if(c){if(!W||!gb)c="";else{c=[];c.push(gb.type);c.push(gb.redirectCount);c.push(Na);for(d=0;d<Nb.length;d++)c.push(tc(Nb[d]));c=c.join("/")}c=";nt="+c}else c="";c=b+c+(q?";ct="+q:"")+(Oa?";gl="+Oa:"")+("device"in a?";device="+escape(a.device):"")+";ni=";if(!D||!D.connection)b="";else{b=D.connection;d=[];for(h=0;h<Ob.length;h++){e=b[Ob[h]];if(void 0!==e)switch(e){case !0:e=1;break;case !1:e=0;break;default:e=(""+e).replace(/\//g,"_")}d.push(e)}b=d.join("/")}return c+
b+("params"in a?";params="+escape(wa(a.params)):"")+(null!==n?";detect="+n:"")+(la||oa?";lvid="+escape([ya,w(),F,ca].join(":")):"")+(A?";opts="+escape(A):"")+(r?";flocid="+escape(r.id)+";flocv="+escape(r.version):"")+("version"in a?";appver="+escape(a.version):"")+(da.support?";visible="+da.getValue():"")+";js=13"}function Pb(a){a=";e="+escape("PVT/"+a);for(var b=0;b<B.length;b++)z(I(B[b],"/tracker",!1,!0)+a)}function Ac(){db=!0;Qb(1);if(!hb&&!za){za=!0;for(var a=0;a<B.length;a++)Fb(B[a])}}function Bc(){Qb(0);
db=!1}function uc(){var a=U(Rb);if(null===a)return null;a=a.split("|");if(2!==a.length)return null;var b=a[1],b=w()-b;if(0>b||b>Sb)return null;a=parseInt(a[0],10);return isNaN(a)?null:a}function Qb(a){var b=w();a=[a,b].join("|");ra(Rb,a,{path:"/",expires:Sb})}function Cc(){Dc||(N.pvt2=setTimeout(function(){Pb(2)},2E3));Ec||(N.pvt15=setTimeout(function(){Pb(15)},15E3))}function Tb(){ib||setInterval(function(){_tmr.beat()},6E4)}function Fc(a,b,c,d){if(!b||!d||d===jb&&b===jb&&c===jb)return null;b={goal:Gc+
b,value:c||0,params:{product_id:d}};a&&(b.id=a);return b}function Pa(){k.addEventListener?(K(k,"DOMContentLoaded",Pa),_tmr.onready()):k.attachEvent&&"complete"===k.readyState&&(K(k,"readystatechange",Pa),_tmr.onready());Ub()}function kb(a){if(ma){if(a.persisted){Aa=Ba=Qa=0;lb=mb=!1;M&&v.launch();a=nb;nb=[];for(var b=0,c=a.length;b<c;b++)_tmr.callbackOnReady(a[b]);a=Ra;Ra={};for(b in a)_tmr.pageView(a[b]);Tb()}}else K(f,"load",kb);_tmr.onready();_tmr.onload()}function Ca(){ma||(K(f,"unload",Ca),K(f,
"beforeunload",Ca));_tmr.unload()}function Ub(){M&&v.launch();if(Hc){window.addEventListener("message",function(a){var c=null;try{if(c=a.data,Q(c)||(c=Vb(c)),"LOAD_BUTTONS_SCRIPT"===c.type){var d;var e=document.referrer;a=null;var h=(""+c.lang).toLowerCase(),g;b:{for(var c=0,l=ob.length;c<l;c++)if(ob[c]===h){g=!0;break b}g=!1}g||(h=ob[0]);try{a=pa.parse(e,"domain")}catch(f){}d=a&&Ic.test(a)?"https://"+a+"/top_constructor/buttons_"+h+".js":Ya("/js/dyn-goal-wizard-"+h+".js");Eb(d)}}catch(k){}});if(window.opener)try{window.opener.postMessage({type:"READY"},
document.referrer)}catch(a){}cb||(Sa.push.apply(Sa,Da),Kb(Da))}}if("[object Array]"===Object.prototype.toString.call(_tmr)){var wb=(new Date).getTime(),Wa=null,Ia=null,Ja=null,S=null,Xa=null,f=window,D=navigator,k=document,x=location,$="string"===typeof x.hostname?x.hostname:"",Ea=-1!=$.search(/(^|\.)odnoklassniki\.ru$/)||-1!=$.search(/(^|\.)ok\.ru$/),Wb=-1!=$.search(/(^|\.)vk\.com$/);$.search(/(^|\.)mail\.ru$/);var Jc=-1!=$.search(/(^|\.)lamoda\.ru$/),Kc=-1!=$.search(/(^|\.)kommersant\.ru$/);$.search(/(^|\.)top\.mail\.ru$/);
$.search(/(^|\.)dzen\.ru$/);var Lc="string"===typeof x.search&&-1!=x.search.search(/[?&]rb_clickid=/),p="string"===typeof x.search&&-1!=x.search.search(/[?&]tmr_debug=1(?:&|$)/),gc=!1,ib=Ea||Wb||Jc||Kc,Dc=!Lc,Ec=Ea,hb=!1,M=f.performance&&"visibilityState"in k,Mc=[36383],Nc=!(Ea||Wb),Hc=!0,Xb=f.JSON&&f.JSON.stringify&&f.JSON.parse,ma="onpageshow"in f&&"onpagehide"in f,wa=Xb?f.JSON.stringify.bind(f.JSON):function(a){return""},Vb=Xb?f.JSON.parse.bind(f.JSON):function(a){return{}},pa=function(){function a(a,
b){var c=(""+a).match(e),d={};d[g]=c;for(var h=0,f=c.length;h<f;h++)c[h]&&(d[n[h]]=c[h]);c=1<arguments.length&&void 0!==b;delete d[g];return c&&!0!==b?d[b]||null:d}function b(a,b){var d;d=(""+a).match(h)||[];var e={};e[g]=d;if(d.length){for(var f=0,l=d.length;f<l;f++)d[f]&&(e[k[f]]=d[f]);d=e}else d=null;if(!d)return null;if((e=1<arguments.length&&void 0!==b)&&(-1!==m.indexOf(b)||!0===b))for(var f=d,n=0,Oc=m.length;n<Oc;n++)(l=c(p[n]||"",f,n))&&(f[m[n]]=l);delete d[g];return e&&!0!==b?d[b]||null:d}
function c(a,b,d){var e="",h;if(Q(a)&&"data"in a)e="index"in a?(b[a.data]||[])[a.index]||"":c(a.data,b,d),"re"in a&&(e=fc(e,a.re,a.reMatchIndex)||""),e&&(h=c(a.pre||"",b,d),a=c(a.post||"",b,d),e=h+e+a);else if(T(a)){h=0;for(var f=a.length;h<f;h++)e+=c(a[h],b,d)}else e=k.indexOf(a),-1===e&&(e=m.indexOf(a),e>=d&&(e=-1)),e=-1!==e?b[a]||"":""+a;return e}function d(a){var b;if(T(a)){b=[];for(var c=0,e=a.length;c<e;c++)b.push(d(a[c]));return b}b=a instanceof RegExp?a:RegExp("^"+zb(a)+"$");return b.test(pa.parse(x.href,
"domain"))?null:b}var e=/^((mailto|tel|fax|modem)\:)(.*)$/,h=/^(?:([a-z]+):(?:([a-z]*):)?\/\/)?(?:([^:@]*)(?::([^:@]*))?@)?(?:((?:[a-z0-9_-]+\.)+[a-z]{2,}|localhost|(?:(?:[01]?\d\d?|2[0-4]\d|25[0-5])\.){3}(?:(?:[01]?\d\d?|2[0-4]\d|25[0-5]))))(?::(\d+))?(?:([^:\?\#]+))?(?:\?([^\#]+))?(?:\#([^\s]+))?$/i,g="_raw",f="hash",f="hash",n=["href","protocol","contactBy","contactTo"],k=["href","scheme","subscheme","user","pass","hostname","port","pathname","query",f],m=["protocol","auth","host","domain","path",
"search",f,"fileExtension"],p=[{data:["scheme",{pre:":",data:"subscheme"}],post:":"},[{data:"user",post:{pre:":",data:"pass"}}],[{data:g,index:5,post:{pre:":",data:"port"}}],{data:"host",re:/^(?:w{3}.)?(.*)$/,reMatchIndex:1},["pathname",{pre:"?",data:"query"}],{pre:"?",data:"query"},{pre:"#",data:f},{data:"pathname",re:/.\.([^\.]+)$/,reMatchIndex:1}];return{parse:function(c,d){return!c?null:e.test(""+c)?a(c,d):b(c,d)},getIsDomainRE:d,getDomainMask:function(a,b,c){b=(b&&0<b?b:2)-1;var d=1;a=(""+a).replace(RegExp("^.*(?:\\.((?:[^\\.]+\\.){"+
b+"}[^\\.]+$))"),"$1");if(d=a.match(/\./g))d=d.length;a="(?:^|\\.{"+(b-d+1)+"})"+zb(a)+"$";return RegExp(c?"^((?!"+a+").)*$":a)}}}(),ob=["ru","en"],Ic=/^(ads\d+\.my\.com)$/,Bb="POST",Cb="application/x-www-form-urlencoded",la=!(0===x.hostname.search(/^(\d+.)+\d+$/g)||-1!==x.hostname.search(/:/g)),ka=null,oa=qc(),ab={domain:rc(),path:"/",expires:287712E5};(function(){var a;if(a=k.cookie.match(RegExp("(?:^|; )(tmr_tcdhn\\d+)=([^;]*)","g"))){for(var b=[],c,d=0,e=a.length;d<e;d++)c=a[d],(c=c.match(/(?:^|; )(tmr_tcdhn\d+)=([^;]*)/))&&
b.push(c.slice(1));a=b}else a=null;if(a){d=0;for(e=a.length;d<e;d++)b=a[d][0],$a(b,ab)}})();var za=!1,db=null,Sb=864E5,Rb="tmr_detect",Pc=function(){function a(a,b){for(var c=a.length,f,l,n=0;n<b;n++)l=Math.floor(Math.random()*c),f=a[n],a[n]=a[l],a[l]=f;return a.slice(0,b)}function b(b,e){var h=k.createElement("div"),f=String.fromCharCode(97,100,118,98,108,111,99,107,32,97,100,118,101,114,116,98,108,111,99,107,32,97,100,118,101,114,116,66,108,111,99,107,32,98,45,114,98,32,98,97,110,110,101,114,95,
50,52,48,32,112,45,116,97,114,103,101,116,32,112,117,98,95,51,48,48,120,50,53,48,32,112,117,98,95,51,48,48,120,50,53,48,109,32,112,117,98,95,55,50,56,120,57,48,32,114,98,95,98,111,100,121,32,114,98,45,102,108,111,97,116,105,110,103,32,114,98,45,115,108,111,116,32,114,98,45,118,105,100,101,111,45,119,105,100,103,101,116,32,116,101,120,116,45,97,100,32,116,101,120,116,45,97,100,45,108,105,110,107,115,32,116,101,120,116,45,97,100,115,32,116,101,120,116,45,98,97,110,110,101,114,32,116,101,120,116,95,
97,100,32,116,101,120,116,95,97,100,115,32,116,101,120,116,65,100,32,116,101,120,116,97,100,32,116,101,120,116,65,100,115,32,116,101,120,116,97,100,115,32,116,103,98,45,98,97,110,110,101,114,32,116,114,103,45,98,45,98,97,110,110,101,114,45,98,108,111,99,107).split(" "),f=a(f,c);h.setAttribute("class",f.join(" "));h.setAttribute("style","position: absolute !important; top: -9999px !important; left: -9999px !important; width: 1px !important; height: 1px !important;");h.setAttribute("id","trg-b-banners-1");
h.setAttribute("data-view","SlotView.mimic");this.bait=k.body.appendChild(h);this.bait.offsetParent;this.bait.offsetHeight;this.bait.offsetLeft;this.bait.offsetTop;this.bait.offsetWidth;this.bait.clientHeight;this.bait.clientWidth;this.loopNumber=0;this.fnPositive=b||null;this.fnNegative=e||null;var l=this;setTimeout(function(){l._checkBait.call(l)},1)}var c=7;b.prototype._checkBait=function(){if(za)this._stop();else{var a=null!==k.body.getAttribute("abp")||!yb(this.bait,!0);(!0===a||10<=++this.loopNumber)&&
this._stop();var b;if(a&&this.fnPositive)try{b=this.fnPositive,b()}catch(c){p&&console.warn("[TopMailRu] Error#1.9",c)}else if(!a&&10>this.loopNumber){var f=this;setTimeout(function(){f._checkBait.call(f)},50*this.loopNumber)}else try{b=this.fnNegative,b()}catch(l){p&&console.warn("[TopMailRu] Error#1.10",l)}}};b.prototype._stop=function(){try{k.body.removeChild(this.bait)}catch(a){p&&console.warn("[TopMailRu] Error#1.11",a)}};return function(a,c){new b(a,c)}}(),C=null,Yb="ecommerce",R="dataLayer",
ea=null,pb=!1,Ta=[],Qc=[36383,2540645,3171181,3074137,2057653],Rc=[],qb;(function(){function a(a,b){for(var c=0,d=b.length;c<d;c++)-1===a.indexOf(b[c])&&a.push(b[c])}function b(b,c,d){for(var e={ecom_method:[],ecom_type:[],ecom_data:{events:[]}},f=0,h=b.length;f<h;f++){var g=s[b[f]];if(g){a(e.ecom_method,[b[f]]);for(var n=0,l=g.length;n<l;n++)for(var k=0,Ka=d.length;k<Ka;k++){var m=g[n][d[k]];if(m)for(var t=0,q=c.length;t<q;t++)if(-1!==g[n].type.indexOf(c[t])){a(e.ecom_type,[c[t]]);a(e.ecom_data.events,
m);break}}}}return e}function c(a,b,c){if(!a||!c||!(b in s))return null;for(var d,e=0,f=s[b].length;e<f;e++)if(d=s[b][e],c in d&&-1!==d[c].indexOf(a))return{ecom_method:[b],ecom_type:d.type.slice(),ecom_data:{}};return null}function d(a){for(var d=[],f,g,m=0,Sc=a.length;m<Sc;m++)if(g=a[m]){f=null;try{if(g.ecommerce)f=e(g)||h(g);else if(null===g.ecommerce)f=null;else if(g.event){var aa={event:g.event,ecommerce:{}};f=e(aa)||h(aa)}else if("event"===g[0]){var Zb=g[1],s=g[2],y=c(Zb,n,r);y&&(y.ecom_data[Zb]=
s);f=y}else if(g.event===Yb)a:{for(var Fa=b([l],[k],[q]),E=0,t=Fa.ecom_data.events.length;E<t;E++)if(!g.hasOwnProperty(Fa.ecom_data.events[E])){f=null;break a}delete Fa.ecom_data.events;Fa.ecom_data[Yb]=g;f=Fa}}catch(A){p&&console.warn("[TopMailRu] Error#1.23",A),f=null}f&&(d.push(f),Ta.push(f))}if(d.length){a=0;for(f=d.length;a<f;a++)Gb(Ua,d[a]);C||(C=[0,0,R]);C[0]+=d.length;f=a=0;for(m=d.length;f<m;f++)a+=wa(d[f].ecom_data).length;C[1]+=a}}function e(a){var b,d;for(d in a.ecommerce)if(a.ecommerce.hasOwnProperty(d)&&
(b=c(d,l,m))){if(a.event&&(d=c(a.event,l,A)))for(var e=0,f=b.ecom_type.length;e<f;e++)-1===d.ecom_type.indexOf(b.ecom_type[e])&&(b.ecom_type.splice(e,1),f--,e--);b.ecom_data=a.ecommerce;return b}return null}function h(a){var b=a.event,d=c(b,l,A);d&&(d.ecom_data[b]=a.ecommerce);return d}function g(a){if((a=f[a])&&"function"===typeof a.push)d(a),ea=a.push,a.push=function(){var a=ea.apply(this,arguments);d([].slice.call(arguments,0));return a}}var l="push",n="gtag",k="gse",m="inner",A="outer",r="external",
q="required",s={};s[n]=[{type:["gee"],external:"add checkout checkout_option checkout_progress click detail promo_click remove select_content set_checkout_option view_refund".split(" ")},{type:["ga4"],external:"earn_virtual_currency join_group level_end level_start level_up post_score select_content spend_virtual_currency tutorial_begin tutorial_complete unlock_achievement ad_impression login search share sign_up add_payment_info add_shipping_info add_to_wishlist generate_lead select_item select_promotion view_cart view_item_list".split(" ")},
{type:["gee","ga4"],external:"add_to_cart begin_checkout purchase refund remove_from_cart view_item view_promotion".split(" ")}];s[l]=[{type:[k],required:["transactionId","transactionTotal"]},{type:["ga4"],outer:b([n],["ga4"],[r]).ecom_data.events},{type:["gee"],inner:"click checkout checkout_option impressions promoClick promoView refund".split(" "),outer:"addToCart checkout checkoutOption productClick productDetail ProductImpressions promotionClick promotionView removeFromCart transactionPush".split(" ")},
{type:["ym","gee"],inner:["add","detail","purchase","remove"]},{type:["mt"],outer:["mt_order","mt_refund"]}];qb=function(a){if(!(a===R&&ea)){a!==R&&(Ta=[]);var b=f[R];b&&"function"===typeof b.push&&ea&&(b.push=ea,ea=null);g(a);pb=!0}}})();var Hb=function(){var a=[{id:"gtag",globalVars:["google_tag_manager"]},{id:"ga",globalVars:["GoogleAnalyticsObject"]},{id:"ym",globalVars:["Ya",{re:"yaCounter\\d+"}]},{id:"vk",globalVars:["VK"]},{id:"vk",globalVars:["vkAsyncInit"]}],b={};return function(){var c;
try{c=Object.keys(f).join(",")}catch(d){c=null}for(var e=[],h,g=0,l=a.length;g<l;g++){h=b[a[g].id];if(void 0===h)a:{h=a[g].globalVars;for(var n=c,k=0,m=h.length;k<m;k++){var p=h[k];if("string"===typeof p&&!(p in f)||"string"===typeof p.re&&(n&&-1===n.search(RegExp("($|,)"+p.re+"(,|^)","m"))||1===m)){h=!1;break a}}h=!0}h&&(b[a[g].id]=!0,L(a[g].id,e)||e.push(a[g].id))}return e}}(),vc=Hb,Jb=864E5,Ib="tmr_floc",Mb=null;(function(a){try{k.interestCohort&&"function"===typeof k.interestCohort&&k.interestCohort().then(function(a){Mb=
{id:a.id,version:a.version};a=[a.id,a.version];var b=w();a=a.concat(b).join("|");ra(Ib,a,{path:"/",expires:Jb})},function(){})}catch(b){}})();var rb=!1,Oa=null,Ga=null,sb=!1,$b;(function(){function a(a){try{var c=a.state;Ga=c in g?g[c]:f;sb=c===e;rb&&b(sb)}catch(d){}}function b(a){try{a?(D[d].getCurrentPosition(c),l||(l=D[d].watchPosition(c))):(l&&D[d].clearWatch(l),c(null))}catch(b){}}function c(a){if(a)try{var b=a.coords,b=[b.latitude,b.longitude,b.accuracy,b.altitude,b.altitudeAccuracy,b.heading,
b.speed];a=0;for(var c=b.length;a<c;a++)"number"!==typeof b[a]&&(b[a]="");b.splice(0,0,Ga);Oa=b.join("/")}catch(d){}else Oa=Ga}var d="geolocation",e="granted",f="u",g={denied:"d"};g[e]="g";g.prompt="p";var l=null;(function(){Ga=f;c(null);try{d in D?D.permissions&&D.permissions.query({name:d}).then(function(b){a(b);b.onchange=function(){a(b)}}):Ga="n"}catch(b){}})();$b=b})();var da={support:!1},da=function(){function a(){e(g)}function b(){e(g,r)}function c(a){a.persisted&&(q[g]=null,q[l]=null,e(g,
p))}function d(){return n?!k[n]:null}function e(a,b){var c=w(),e="undefined"===typeof b?d():b;if(null===q[a])q[a]={ts:c,state:e,total:0};else{var f=q[a];if(f.state!==e&&!(f.state===r&&e!==p)){var g=c-f.ts,l=f.state;f.ts=c;f.state=e;g<h||(l===p?(f.total+=g,v&&v(c,g)):l===A&&u&&u(c,g))}}}var h=5,g="auto",l="user",n=null,m=null,p=!0,A=!1,r=null;"hidden"in k?(n="hidden",m="visibilitychange"):"mozHidden"in k?(n="mozHidden",m="mozvisibilitychange"):"webkitHidden"in k?(n="webkitHidden",m="webkitvisibilitychange"):
"msHidden"in k&&(n="msHidden",m="msvisibilitychange");var q={};q[g]=null;var v=q[l]=null,u=null;return{support:!!n,auto:function(d,e){v=d||null;u=e||null;n&&(a(),s(k,m,a));ma?(s(f,"pageshow",c),s(f,"pagehide",b)):(s(f,"beforeunload",b),s(f,"unload",b))},set:function(a){e(l,!!a)},getLog:function(){var a=w(),b={},c,d;for(d in q)c=q[d],b[d]=c?c.total:0,c&&c.state&&(b[d]+=a-c.ts);return b},getValue:d}}();da.auto();var ac={enabled:!1},bc=function(){var a="checkbox color date datetime-local email file month number password radio range search tel text time url week".split(" ");
return{analyze:function(b){if(!b)return null;for(var c=[].slice.apply(b.elements),d=[],e=[],f=0,g=c.length;f<g;f++){var l;a:switch(l=c[f],l.tagName.toLowerCase()){case "button":l=!1;break a;case "input":var k=l.type.toLowerCase();if(k&&-1===a.indexOf(k)){l=!1;break a}default:l=yb(l,!1)&&l.name&&!1===l.disabled}l&&(d.push(c[f].name),e.push(c[f].type))}return{node:b,inputsName:d.length?d:null,inputsType:e.length?e:null}},getFormByInput:function(a){if(!a)return null;a=a.form||a.getAttribute("form");
return"string"===typeof a?document.getElementById(a)||null:a instanceof HTMLElement?a:null}}}(),ac=function(){function a(a){a=a||f.event;var c=(a.which||a.keyCode)===K;if("which"in a&&a.which===B||"button"in a&&a.button&B||c){a:{a=a.target||a.srcElement;for(var c=0,d=g.length;c<d;c++){var k;b:{k=a;for(var y=g[c],q=0,E=y.types.length;q<E;q++){var t;c:{var s=k;t=y.types[q];var r=null;if(t.filter.tagName)for(var J=0,u=t.filter.tagName.length;J<u&&!(r=xb(s,t.filter.tagName[J]));J++);else r=s;if(r){if(t.filter.attr)for(s in s=
void 0,t.filter.attr)if(t.filter.attr.hasOwnProperty(s)&&(J=t.filter.attr[s],u=r[s],!0===J&&!u||!1===J&&u||T(J)&&-1===J.indexOf(u))){t=null;break c}t={source:r,type:t.type,detail:r.tagName}}else t=null}if(t){t.category=y.category;k=t;break b}}k=null}if(k){a=k;break a}}a=null}if(a){if(a.category===e){if(a.data=pa.parse(a.source.href,!0),!a.data)return}else if(a.category===h){if(a.data=bc.analyze(bc.getFormByInput(a.source)),!a.data)return}else return;c=I;if(c.enabled&&c.modes){d=0;for(k=c.modes.length;d<
k;d++)if(y=a,q=c.modes[d],y.category===q.mode)if(y.category===e||y.category===h){if(q=q.categories,y.data){E=void 0;c:{E=0;for(t=q.length;E<t;E++){for(var r=y,s=q[E],J={category:y.category},u=[],z=0,fa=s.types.length;z<fa;z++){var x=s.types[z],C=ja({type:s.category},J),L=A in x,D;v in x?D=b(r,x,C,v):L&&(D=ja({source:r.source,data:r.data,detail:x.type},C));if(D&&(!L||!b(r,x,C,A)))if(u.push(D),(x.rule&w)!==w)break}if(r=u.length?u:null){E=r;break c}}E=null}if(E){y=0;for(q=E.length;y<q;y++)c:{t=E[y];
r={type:"sendEvent",category:"_"+t.category,action:t.detail};if(t.category===e&&(t.type===l||t.type===n)){if(r.label=t.data.href,!r.label)break c}else if(t.category===m&&(r.label=t.data.node.action,!r.label))break c;_tmr.push(r)}}}}else p&&console.warn("[TopMailRu] Error#1.24","Not found tracking for type",y.type)}}}}function b(a,b,d,f){var e=!1,g=b[f];if(T(g)){var h=b[f+"Rule"]||z;f=(h&r)===r;for(var h=(h&q)===q,k=0,l=g.length;k<l&&!(e=c(a,g[k]),f&&e);k++)if(h&&!e)return null}else e=c(a,g);return!e?
null:ja({source:a.source,data:a.data,detail:b.type},d)}function c(a,b){var c=b.rule||z,f=(c&r)===r,c=(c&q)===q,e=!1,g;for(g in b)if(b.hasOwnProperty(g)&&"rule"!==g){var e=b[g],h=a.data[g],e=!0===e?!!(T(h)?h.length:h):!1===e?!(T(h)?h.length:h):d(h,e);if(f&&e)break;else if(c&&!e)return!1}return e}function d(a,b){var c=a;if(c)if(T(c)){if(!c.length)return!1}else c=[c];else return!1;var d=b,e=z;if(Q(d)&&!T(d)){if(!T(d.value))return!1;e=d.rule||e;d=d.value}a:{for(var f=(e&u)===u,g=(e&r)===r,e=(e&q)===q,
h=!1,k=0,l=d.length;k<l;k++){var n=d[k];if(n){var m="string"===typeof n;m&&!f&&(n=n.toLowerCase());var s=n instanceof RegExp;if(m||s){var h=!0,p;b:{p=c;for(var v=f,w=0,A=p.length;w<A;w++){var x=v?p[w]:p[w].toLowerCase();if(s&&n.test(x)||m&&n===x){p=!0;break b}}p=!1}if(g&&p){c=!0;break a}else if(e&&!p){c=!1;break a}}}}c=g?!1:e?h?!0:!1:void 0}return c}var e="click",h="submit",g=[{category:h,types:[{type:"button",filter:{tagName:["input","button"],attr:{type:["submit","image"]}}}]},{category:e,types:[{type:"a",
filter:{tagName:["a"],attr:{href:!0}}}]}],l="file",n="resource",m="submit",v="filter",A="stop",r=1,q=2,u=4,w=8,z=r,I={enabled:!0,modes:[{mode:h,categories:[{category:m,types:[{type:"lead",filter:[{inputsName:["phone"],inputsType:["tel"],rule:r},{inputsName:["email"],inputsType:["email"],rule:r}],filterRule:q,stop:{inputsName:{value:["password"]}}},{type:"form",filter:{inputsName:!0}}]}]},{mode:e,categories:[{category:"contact",types:[{type:"email",filter:{contactBy:["mailto"]}},{type:"phone",filter:{contactBy:["tel"]}}]},
{category:l,types:[{type:"file",filter:{fileExtension:"7z bz2 gz apk iso cab dmg msi rar tar zip exe txt doc docx ppt pptx xls xlsx csv pdf psd rtf ods djvu eps 3gp aac ac3 avi flac flv divx midi mka mkv mp3 mp4 mpeg mpg mov ogg vob wav webm wma wmf wmv torrent".split(" ")}}]},{category:n,types:[{type:"outgoing",rule:w,stop:{domain:[pa.getDomainMask(pa.parse(x.href,"domain"),3,!1)],href:[/password/]}},{type:"messenger",filter:{domain:pa.getIsDomainRE("vk.me t.me telegram.me telegram.im web.telegram.org m.me web.whatsapp.com api.whatsapp.com chat.whatsapp.com wa.me".split(" "))},
stop:{href:[/password/]}},{type:"social",filter:{domain:pa.getIsDomainRE("vk.com vkontakte.ru m.vk.com vk.ru ok.ru m.ok.ru odnoklassniki.ru facebook.com m.facebook.com fb.com twitter.com linkedin.com instagram.com tiktok.com youtube.com youtu.be m.youtube.com".split(" "))},stop:{href:[/password/]}}]}]}]},B=1,K=13;return{enabled:!0,start:function(){s(k,"click",a);s(k,"keypress",a)}}}();Nc&&ac.start();var v=function(){function a(){b(null)}function b(a){e();a?(U=a===fa,na=a):na=Z&&null!==U?U?fa:$:k.visibilityState;
a=aa();for(var b in ga)v(b,a)}function c(){if(!1!==P){K(f,Y,ia);ia=null;f.clearInterval(ka);la=ka=null;K(k,J,ca);ca=null;Z&&(K(f,V,da),K(f,W,ea),ea=da=null);h(!0);for(var a in ba){var b=a,c=ba[b];c&&(c=c.key,M(b),F(),delete ba[b],y(null,c))}G=null;ha=[];ua=[];H={};ba={};ga={};P=!1}}function d(a,b,c){var d=a+"_"+b;if(d in H)return!1;var e=w(),f=aa(),g=B(d,e,fb);b=H[d]={id:a||null,name:b,key:g,canUseInBackground:!!c,startTS:e,updateTS:f,timespent:{}};if(a)if(ua.push(d),d=b.canUseInBackground,b=ga[a]){if(c=
b.isActive,!c&&(e=G&&L(a,G)))if(c=na===fa||d)b.updateTS=f,b.isActive=!0}else e=G&&L(a,G),c=na===fa||d,ga[a]={isActive:e&&c,updateTS:f,timespent:{}};else ha.push(d);return!0}function e(a,b){var c,d;2>arguments.length?(c=ua.concat(ha),d=E):(c=[a+"_"+b],d=R);g(c,d)}function h(a,b,c){var d=!1,e=[],f=[];2>arguments.length?(e=ua.slice(),(d=!!arguments[0])&&(e=e.concat(ha))):(d=a+"_"+b,-1!==ua.indexOf(d)?e=[d]:-1!==ha.indexOf(d)&&(c?e=[d]:f=[d]));g(e,X);g(f,R)}function g(a,b){var c=aa(),d=[],e,f,g;e=0;for(f=
a.length;e<f;e++)g=a[e],-1!==ua.indexOf(g)?l(g,b,c):-1!==ha.indexOf(g)&&d.push(g);e=0;for(f=d.length;e<f;e++)g=d[e],l(g,b,c);if(b===E&&(S=c,S-P>=qa)){for(var h in H)m(h);for(h in ba)if(c=h,d=ba[c])M(c),y(c,d.key);P=S}}function l(a,b,c){var d=H[a];if(d&&!1!==d.updateTS)if(d.timespent[na]=(d.timespent[na]||0)+(c-(d.updateTS||S)),-1!==ha.indexOf(a)&&x(null,c),b===X)d.updateTS=!1,m(a);else if(b===t){d.updateTS=c;var e;a:{if(b=H[a])for(e in b.timespent)if(b.timespent[e]>pa){e=!1;break a}e=!0}e?(n(a),F()):
m(a)}else d.updateTS=b===E?null:c,n(a),F()}function n(a,b,c){var d=H[a];if(!d)return null;var e=b||d.key;b=O[e];O[e]={uid:a,name:d.name,counterID:c||d.id||G,canUseInBackground:d.canUseInBackground,isActive:!1!==d.updateTS,startTime:d.startTS,timespent:{}};a=O[e].timespent;var d=d.timespent,f;for(f in d)a[f]=d[f];if(c&&(c=ga[c]))if(e=O[e]){e.common={};e=e.common;c=c.timespent;for(var g in c)e[g]=c[g]}return b||null}function m(a){var b=H[a];b&&(n(a),p(a,b.key))}function p(a,b){var c=O[b];if(c)if(T(c.counterID)){var d=
O[b];if(d){var c=d.counterID,e=[],f,g,h,k;if(c){h=0;for(k=c.length;h<k;h++){g=c[h];f=B(b,g);e.push(f);g=n(a||d.uid,f,g);var l=void 0;g&&(l=O[f],N(l.timespent,g.timespent),g.common&&(l.common=l.common||{},N(l.common,g.common)))}}delete O[b];F();if(a&&a in H)if(d.isActive){r(a);h=0;for(k=c.length;h<k;h++)if(d=ga[c[h]])for(var m in d.timespent)d.timespent[m]=0}else q(a);h=0;for(k=e.length;h<k;h++)u(e[h])}}else if(m=O[b])(c=a&&a in H)&&!m.isActive&&q(a),e=u(b),c&&(e&&m.isActive)&&r(a)}function u(a){var b;
if(b=O[a]){var c=Q(b.timespent);if(!1===b.canUseInBackground&&b.isActive&&0===c.fg)b=null;else{c=[b.name,b.startTime,b.canUseInBackground?1:0,c.fg,c.bg];if(b.common){var d=Q(b.common);(d.fg||d.bg)&&c.push(d.fg,d.bg)}b={id:b.counterID,msg:c.join("/")}}}else b=!1;if(!b)return!1;c=";e="+escape("TS:"+b.msg);z(I({id:b.id},"/tracker",!1,!1)+c);delete O[a];F();return!0}function r(a){if(a=H[a])for(var b in a.timespent)a.timespent[b]=0}function q(a){if(a in H){var b;-1!==(b=ha.indexOf(a))&&ha.splice(b,1);
if(-1!==(b=ua.indexOf(a)))if(ua.splice(b,1),b=H[a].id){var c=ga[b];if(c){var d=c.isActive;d&&D(c,aa());d=C(b,a);d||(c.isActive=!1)}}delete H[a]}}function v(a,b){var c=ga[a];if(c){var d=G&&L(a,G),e=C(a);c.isActive=d&&e;c.updateTS=b}}function x(a,b){if(a){var c=ga[a];c&&(c.isActive?D(c,aa()):c.updateTS=b)}else for(c in ga)x(c,b)}function C(a,b){for(var c in H)if(c!==b&&H[c].id===a&&(na===fa||H[c].canUseInBackground))return!0;return!1}function D(a,b){a&&(a.timespent[na]=(a.timespent[na]||0)+(b-a.updateTS),
a.updateTS=b)}function B(a){return[].join.call(arguments,"_")}function N(a,b){for(var c in b)a[c]=(a[c]||0)+(b[c]||0)}function Q(a){var b=a[fa]||0,c=0,d;for(d in a)d!==fa&&(c+=a[d]);return{fg:b,bg:c}}function aa(){return Math.floor(f.performance.now())}function F(){if(oa){var a={};a[sa]=O;a[ta]=va;Ma(ra,wa(a)||"")}}function M(a){var b=ba[a];b&&(va[b.key]={uid:a,name:b.name,counterID:b.id,value:b.value})}function y(a,b){if(va[b]){var c;if(c=va[b])if(0===c.value)c=null;else{var d=[c.name,c.value].join("/");
c={id:c.counterID,msg:d}}else c=!1;c&&(d=";e="+escape("TS:"+c.msg),z(I({id:c.id},"/tracker",!1,!1)+d));!1!==c&&(delete va[b],F());if(c&&a&&(c=ba[a]))c.value=0}}var R=1,E=2,t=4,X=8,Y=ma?"pagehide":"unload",J="visibilitychange";"mozHidden"in k?J="mozvisibilitychange":"webkitHidden"in k?J="webkitvisibilitychange":"msHidden"in k&&(J="msvisibilitychange");var V="focus",W="blur";"onfocusin"in k&&(V="focusin",W="focusout");var fa="visible",$="hidden",ja=["0"],Z=!1,pa=100,qa=12E4,P=!1,S=!1,G=null,ha=[],ua=
[],H={},na,U=null,ka,la,ca,da,ea,ia,ra="tmr_tslog",sa="activity",ta="count",O={},ba={},va={},ga={};return{init:function(){if(oa){var a=Vb(La(ra)||"{}");O=a[sa]||{};va=a[ta]||{}}for(var b in O)p(null,b);for(b in va)y(null,b)},launch:function(){!1===P&&(P=aa(),S=aa(),na=Z&&null!==U?U?fa:$:k.visibilityState,ia=c.bind(f),s(f,Y,ia),la=a.bind(f),ka=f.setInterval(la,1E4),ca=b.bind(f,null),s(k,J,ca),Z&&(da=b.bind(f,fa),ea=b.bind(f,$),s(f,V,da),s(f,W,ea)))},enable:function(a){if(G){if(L(a,G))return;g(ha,t)}else{for(var b=
0,c=ja.length;b<c;b++)d(null,ja[b],!1);G=[]}G.push(a);v(a,aa())},disable:function(a){if(G){var b;a:{b=0;for(var c=G.length;b<c;b++)if(G[b]==a)break a;b=-1}if(-1!==b&&(g(ha,t),G.splice(b,1),b=aa(),a=ga[a]))a.isActive=!1,a.updateTS=b}},startActivity:d,updateActivity:e,stopActivity:h,incCount:function(a,b){var c=a+"_"+b,d;if(!(d=ba[c]))if(c in ba)d=ba[c];else{d=w();var e=B(b,d,fb);d=ba[c]={id:a,name:b,key:e,startTS:d,value:0}}d&&d.id===a&&(d.value++,M(c),F())},defaultID:function(){return G?G[0]:void 0}}}(),
cb=!1,zc="60.3.0",Qa=0,Ba=0,fb=Ab(16),Y=null,Z=null,Aa=0,ta="tmr_reqNum",F=null;la&&(F=U(ta)||null,null!==F&&$a(ta,ab));oa&&null===F&&(F=La(ta)||null);F=null===F?0:parseInt(F,10);oa&&Ma(ta,F);var ca=(la?U("tmr_lvid"):null)||(oa?La("tmr_lvid"):null),ya=(la?U("tmr_lvidTS"):null)||(oa?La("tmr_lvidTS"):null);if(null===ca||-1===ca.search(/^[0-9a-fA-F]+$/))ca=Ab(32);Db("tmr_lvid",ca);if(null===ya||-1===ya.search(/^\d+$/))ya=""+w();Db("tmr_lvidTS",ya);var V=0,B=[],Da=[],Va=[],Ua=[],Sa=[],Ra={},xc="ontouchstart"in
f||1<(D.maxTouchPoints||D.msMaxTouchPoints)?"1":"0",yc=f.devicePixelRatio||0,cc=f.performance||f.mozPerformance||f.msPerformance||f.webkitPerformance||{},W=cc.timing||{},gb=cc.navigation||{},Nb="unloadEventStart unloadEventEnd redirectStart redirectEnd fetchStart domainLookupStart domainLookupEnd connectStart connectEnd secureConnectionStart requestStart responseStart responseEnd domLoading domInteractive domContentLoadedEventStart domContentLoadedEventEnd domComplete loadEventStart loadEventEnd".split(" "),
Na=!W?void 0:W.navigationStart,S=Na,Ob="downlink downlinkMax effectiveType rtt saveData type".split(" "),qa,tb;qa=function(a,b,c){if(b&&"object"===typeof b){var d="id"in b&&b.id||V,e=c.title||null,f,g=tb(b,{params:c.required,fn:c.fn});if(g.missed.length)console.warn("[TopMailRu]"+(d?"["+d+"]":"")+" Error#1.14","Unspecified "+(1<g.missed.length&&g.missed.slice(0,-1).join(", ")+" and "||"")+g.missed.slice(-1)+" in "+a);else{var k=tb(b,{params:c.optional,fn:c.fn});f=[].concat(g.values).concat(k.values);
g=[].concat(g.missed).concat(k.missed);c.value&&(b="value"in b&&b.value,!0!==c.value&&(b=b||c.value),b?f.push("value: "+b):g.push("value"));c=f.length?"{ "+f.join(", ")+" }":"";f=g.length?"("+(1<g.length?g.slice(0,-1).join(", ")+" and "+g.slice(-1)+" are":g.slice(-1)+" is")+" empty)":"";d?console.info("[TopMailRu]["+d+"]: "+(e||a)+" "+c+" "+f):console.warn("[TopMailRu] Error#1.15","Undefined counter ID of "+a+" "+c)}}else console.warn("[TopMailRu][]["+a+"] Error#1.13")};tb=function(a,b){var c=[],
d=[],e,f,g;if(b.params)for(e in b.params)if(b.params.hasOwnProperty(e)&&!1!==b.params[e])if(f=e in a&&a[e],!0!==b.params[e]&&(f=f||b.params[e]),f)try{g=b.fn?b.fn:null,c.push(e+': "'+(g?g(e,f):f)+'"')}catch(k){console.warn("[TopMailRu] Error#1.16",k)}else d&&d.push(e);return{values:c,missed:d}};var N={},nb=[];m.prototype.callbackOnReady=function(a){p&&qa("onReady",a,{title:"OnReady callback"});a&&"object"===typeof a&&"function"===typeof a.callback&&(a.callback.call(a.context||null),ma&&nb.push(a))};
m.prototype.pageView=function(a){sa(a);a:if(a&&"object"===typeof a&&a.id){5>Da.length&&!L(a.id,Da)&&(Da.push(a.id),!1!==a.beat&&Va.push(a.id),B.push(a),za&&Fb(a));ma&&(Ra[a.id]=ja(!0,{},a),Ra[a.id].bfCache=!0);"detectBlocker"in a&&!a.detectBlocker&&(hb=!0);var b="string"===typeof a.ecommerce,c=b&&-1!==a.ecommerce.search(/\S/);if(5>Ua.length&&!L(a.id,Ua)&&(!0===a.ecommerce||b&&!c||b&&c||!1!==a.ecommerce&&!b&&(L(a.id,Qc)||!L(a.id,Rc)))){Ua.push(a.id);if(b&&c){if(pb&&(qb(a.ecommerce),R!==a.ecommerce)){R=
a.ecommerce;C&&(C=[0,0,R]);break a}R=a.ecommerce;C&&(C=[0,0,R])}b=[a.id];if(pb)for(var c=0,d=Ta.length;c<d;c++)Gb(b,Ta[c])}a.timespent=M&&(a.timespent||L(a.id,Mc)&&!1!==a.timespent);M&&(a.timespent?v.enable(a.id):v.disable(a.id));rb||(rb=!0===a.geolocation||a.timespent&&!1!==a.geolocation)&&$b(sb);cb&&!L(a.id,Sa)&&(Sa.push(a.id),Kb([a.id]))}p&&qa("pageView",a,{title:"Page view",optional:{url:x.href}});X(a)&&(z(I(a,"/counter",!1,!0)),Ba=w())};m.prototype.reachGoal=function(a){sa(a);p&&qa("reachGoal",
a,{title:"Reach goal",value:!0,required:{goal:!0}});if(X(a)&&"goal"in a&&a.goal){var b="value"in a&&a.value?parseInt(a.value)||"":"";z(I(a,"/tracker",!1,!0)+(";e="+escape("RG:"+b+"/"+a.goal)))}};var jb="VALUE";m.prototype.itemView=function(a){p&&qa("itemView",a,{title:"Item view",optional:{list:!0,pagetype:!0,productid:!0,totalvalue:!0},fn:function(a,b){return(""+b).replace(/;/g," ")}});if(X(a)){var b=a.list||"",c=a.productid||"",d=a.pagetype||"",e=a.totalvalue||0,f=Fc(a.id,d,e,c);f&&this.reachGoal(f);
(new Image).src="https://ad.mail.ru/retarget/?counter="+(a.id||V)+"&list="+b+"&productid="+c+"&pagetype="+d+"&totalvalue="+e+"&_="+Math.random();b="IV:"+e+"/"+(""+b).replace(/;/g," ")+";"+(""+c).replace(/;/g," ")+";"+(""+d).replace(/;/g," ");z(I(a,"/tracker",!1,!0)+(";e="+escape(b)))}};var Gc="vk_ecom_";m.prototype.sendEvent=function(a){sa(a);p&&qa("sendEvent",a,{title:"Send event",value:!0,required:{category:!0,action:!0},optional:{label:!0},fn:function(a,b){return(""+b).substring(0,300).replace(/;/g,
" ")}});if(X(a)&&"category"in a&&a.category&&"action"in a&&a.action){var b=(""+a.category).substring(0,300),c=(""+a.action).substring(0,300),d="label"in a&&a.label?(""+a.label).substring(0,300):"",b="CE:"+("value"in a&&a.value?parseInt(a.value)||"":"")+"/"+(""+b).replace(/;/g," ")+";"+(""+c).replace(/;/g," ")+";"+(""+d).replace(/;/g," ");z(I(a,"/tracker",!1,!0)+(";e="+escape(b)))}};m.prototype.setUserID=function(a){if(null===a||!1===a||void 0===a)this.deleteUserID();else{var b=typeof a;"number"!==
b&&"string"!==b?p&&console.warn("[TopMailRu] Error#1.17","Invalid user ID in setUserID"):(Y=a,p&&console.info("[TopMailRu]: Global user ID = "+Y))}};m.prototype.getUserID=function(){return Y||0===Y?Y:void 0};m.prototype.deleteUserID=function(){Y=null;p&&console.info("[TopMailRu]: Reset global user ID to null")};m.prototype.setUserParams=function(a){if(null===a||!1===a||void 0===a)this.deleteUserParams();else if(Q(a)){try{Z=ja(!0,{},a)}catch(b){p&&console.warn("[TopMailRu] Error#1.22","Invalid user params in setUserParams");
return}p&&console.info("[TopMailRu]: Global user params = "+wa(Z))}else p&&console.warn("[TopMailRu] Error#1.21","Invalid user params in setUserParams")};m.prototype.getUserParams=function(){var a=Z?Z:void 0;return a?ja(!0,{},a):void 0};m.prototype.deleteUserParams=function(){Z=null;p&&console.info("[TopMailRu]: Reset global user params to null")};m.prototype.getClientID=function(){var a=ca;return a||0===a?a:void 0};m.prototype._MT_event=function(a,b,c){sa(a);p&&qa(b,a,{title:c});X(a)&&z(I(a,"/tracker",
!1,!0)+(";e="+escape("MT:/"+b)))};m.prototype.miniAppEvent=function(a){this._MT_event(a,"miniAppEvent","VK Mini App Event")};var ub=function(a,b){if(M){var c=v.defaultID();X(a,c)&&(!Q(a)||!("activity"in a&&a.activity)?p&&console.warn("[TopMailRu] Error#1.27","Invalid startActivity command: ID of activity is required"):v.startActivity(a.id||c,""+a.activity,null===b?!!a.canUseInBackground:b))}};m.prototype.startTimespent=function(a){ub(a,null)};m.prototype.startForegroundTimespent=function(a){ub(a,
!1)};m.prototype.startAnytimeTimespent=function(a){ub(a,!0)};m.prototype.updateTimespent=function(a){if(M){var b=v.defaultID();X(a,b)&&(!Q(a)||!("activity"in a&&a.activity)?v.updateActivity():"number"===typeof a.activity||"string"===typeof a.activity?v.updateActivity(a.id||b,""+a.activity):p&&console.warn("[TopMailRu] Error#1.28","Invalid updateActivity command: ID of activity should be number or string"))}};m.prototype.stopTimespent=function(a){if(M){var b=v.defaultID();X(a,b)&&(!Q(a)||!("activity"in
a&&a.activity)?v.stopActivity(!1):"number"===typeof a.activity||"string"===typeof a.activity?v.stopActivity(a.id||b,""+a.activity,!1):p&&console.warn("[TopMailRu] Error#1.29","Invalid stopActivity command: ID of activity should be number or string"))}};m.prototype.incrementEventTimespent=function(a){if(M){var b=v.defaultID();X(a,b)&&(!a||!("activity"in a&&a.activity)?p&&console.warn("[TopMailRu] Error#1.31","Invalid incrementEventTimespent command: ID of countable activity is required"):v.incCount(a.id||
b,""+a.activity))}};m.prototype.processEvent=function(a,b){if(a&&"object"===typeof a)if("type"in a){if("onready"===a.type){if(b&&0>b)return;this.callbackOnReady(a)}else if(b&&0<b)return;switch(a.type){case "pageView":this.pageView(a);break;case "reachGoal":this.reachGoal(a);break;case "itemView":this.itemView(a);break;case "sendEvent":this.sendEvent(a);break;case "setUserID":"userid"in a&&this.setUserID(a.userid);break;case "deleteUserID":this.deleteUserID();break;case "setUserParams":"params"in a&&
this.setUserParams(a.params);break;case "deleteUserParams":this.deleteUserParams();break;case "miniAppEvent":this.miniAppEvent(a);break;case "startTimespent":this.startTimespent(a);break;case "startForegroundTimespent":this.startForegroundTimespent(a);break;case "startAnytimeTimespent":this.startAnytimeTimespent(a);break;case "updateTimespent":this.updateTimespent(a);break;case "stopTimespent":this.stopTimespent(a);break;case "incrementEventTimespent":this.incrementEventTimespent(a)}}else p&&console.warn("[TopMailRu] Error#1.19",
"Unspecified type of push event");else p&&console.warn("[TopMailRu] Error#1.18","Invalid push event")};m.prototype.push=function(a){for(var b=0,c=arguments.length;b<c;b++)this.processEvent(arguments[b])};var dc=!1;m.prototype.onready=function(){dc||(dc=!0,!hb&&!za&&Pc(Ac,Bc),qb(R))};var mb=!1;m.prototype.onload=function(){if(!mb){mb=!0;Aa=w();if(!Ea&&0<B.length){for(var a=";e="+escape("RT/load")+";et="+Aa,b=0;b<B.length;b++)z(I(B[b],"/tracker",!0,!0)+a);Ba=Aa}Cc()}};m.prototype.beat=function(){var a;
if(!ib&&Qa){var b=w();if(!(12E4<b-Qa)){if(12E4<b-Ba){a=";e="+escape("RT/resend")+";et="+Aa;for(var c=0;c<B.length;c++)!1!==B[c].beat&&z(I(B[c],"/tracker",!1,!0)+a)}else 0<Va.length&&(a=";e="+escape("RT/beat")+";ids="+escape(Va.join()),z(I({id:Va[0]},"/tracker",!1,!0)+a));Ba=b}}};var lb=!1;m.prototype.unload=function(){if(!lb){lb=!0;if(!Ea){var a;a=(a=Lb())?w()-a:void 0;a=";e="+escape("RT/unload")+";et="+w()+(a?";pvt="+escape(a):"");if(da.support){var b=da.getLog();a+=";vtauto="+b.auto}for(b=0;b<B.length;b++)z(I(B[b],
"/tracker",!1,!0)+a)}ma&&(N.pvt2&&(clearTimeout(N.pvt2),delete N.pvt2),N.pvt15&&(clearTimeout(N.pvt15),delete N.pvt15),N.beat&&(clearInterval(N.beat),delete N.beat))}};m.prototype.activity=function(a){Qa=w()};var ia=_tmr;_tmr=new m;M&&v.init();for(var u=0,Ha=ia.length,P;u<Ha;u++)(P=ia[u])&&"object"===typeof P&&sa(P);Wa=(new Date).getTime();u=0;for(Ha=ia.length;u<Ha;u++)P=ia[u],_tmr.processEvent(P,1);Ia=(new Date).getTime();u=0;for(Ha=ia.length;u<Ha;u++)P=ia[u],_tmr.processEvent(P,-1);"complete"===
k.readyState||"loading"!==k.readyState&&!k.documentElement.doScroll?(_tmr.onready(),Ub()):k.addEventListener?s(k,"DOMContentLoaded",Pa):k.attachEvent&&s(k,"readystatechange",Pa);if("complete"===k.readyState)_tmr.onload();else ma?s(f,"pageshow",kb):s(f,"load",kb);ma?s(f,"pagehide",Ca):(s(f,"unload",Ca),s(f,"beforeunload",Ca));Tb();if(!ib)try{for(var ec="scroll gesturechange touchmove mousedown mousemove mouseup touch".split(" "),Tc=function(a){s(k,a,function(){_tmr.activity(a)})},u=0;u<ec.length;u++)Tc(ec[u]);
s(f,"scroll",function(){_tmr.activity("scallback")})}catch(Uc){p&&console.warn("[TopMailRu] Error#1.20",Uc)}Ja=(new Date).getTime()}})();
